name: collecte
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Launch collecte
      run: |
          pip install -r requirements.txt
          python collecte.py
    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add current.csv
        git add archives/
        timestamp=$(date -u)
        git commit -m "Adds latest ANJ files" || exit 0
        git push
